[package]
name = "test-vectors"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies.test-vectors-macro]
path = "../macro"
version = "^0.1.0"
